apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bff-service.fullname" . }}
  labels:
    {{- include "bff-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "bff-service.databaseUrl" . | quote }}
  SECRET_KEY: {{ .Values.app.secretKey | quote }}
